version: '3.3'
services:
  db:
    image: mysql:5.7
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_example'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'springuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ThePassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Ddixit90@'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql
# Names our volume
volumes:
  db-data: